[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "C93fyDjEmyAfr9nwDeWMVCeWVVx8fjySxnshSA9VY4KG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
