[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_anchor = "7UMEGk3CQ1P4fg7xHm1ZnKGZWP1jT3XobP3oiW1JRtB8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
