[features]
seeds = true
skip-lint = false

[programs.localnet]
counter = "GdVMAxhWaxLEZwrmHLWNPXcEjX6PbpPLwMDPRaarhEjD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
