[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "G4HE8NNmb7FaSAyB66H2eU2AvHdBKkQb3LYbaLzChy8q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
